name: chichanka_perfume
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:

  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  connectivity_plus: ^6.1.3 
  crypto: ^3.0.6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_rating_bar: ^4.0.1
  flutter_swipe_action_cell: ^3.1.5
  # flutter_zalopay_sdk: ^0.1.14
  fluttertoast: ^8.2.8
  get: ^4.7.2
  google_sign_in: ^6.1.5
  http: ^1.2.1
  image_card: ^0.0.4
  image_picker: ^1.0.7
  intl: ^0.20.2
  lottie: ^3.3.1
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  flutter_paypal_payment: ^1.0.8
  app_links: ^6.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
